# Site settings
title: Materials Informatics Course Blog
email: tony.fast@gmail.com
description: > 
  Course Blog Page for the GT Materials Informatics Course
baseurl: "/Materials-Informatics-Lab" # the subpath of your site, e.g. /blog/
url: "http://tonyfast.com" # the base hostname & protocol for your site
twitter_username: docfast
github_username:  tonyfast
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
